#!/usr/bin/env ruby
require 'optparse'
require 'vector_be_winding'

opt = OptionParser.new

@dry_run = false
@verbose = false
@debug = false
@backup_template = '%{p}.bak'

opt.on('-n', 'Dry run') { @dry_run = true }
opt.on('-v', 'Verbose') { @verbose = true }
opt.on('-d', 'Debug') { @debug = true }
opt.on('-i TEMP', 'Template of back-up filename. Default; ".bak"') { |temp|
  @backup_template = if temp.index('%')
                      temp
                    else
                      '%{p}' + temp
                    end
}

opt.parse!(ARGV)

ARGV.each { |file|
  drawable = VectorBeWinding::Drawable.new
  drawable.read_from_file(file)
  if !drawable.is_winding
    print "Not winding: #{file}\n" if @verbose
    drawable.dump if @debug

    if !@dry_run
      args = {
        d: File.dirname(file),
        p: file,
        r: File.basename(file, File.extname(file)),
        e: File.extname(file)
      }

      File.rename(file, @backup_template % args)
      drawable.be_winding
      drawable.dump if @debug
      drawable.write_to_file(file)
    end
  end
}
